export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_CURRENT_TODO = 'UPDATE_CURRENT_TODO';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const SET_COMPLETED_ITEMS_VISIBILITY = 'SET_COMPLETED_ITEMS_VISIBILITY';
